---
title: "EXP_CNV_regression"
author: "Arne Weigelt"
date: "09/07/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

CNV_EXPR_REGRESSION
missing expr values aus cnv imputieren
THIS CHUNK IS FROM THE COMBINED RMD, WHICH IS WHY THE DFs ARE CALLED CORR_CLEANED
```{r Sortieren von exp und cnv}
#identify missing rows in exp that are present in cnv
diff_rows= setdiff(rownames(prism.cnv), rownames(prism.exp))
diff_rows= unique(c(diff_rows, setdiff(rownames(prism.exp), rownames(prism.cnv))))
print(diff_rows)

#prism.cnv_corr_cleaned<-prism.cnv[-c("ACH-000309","ACH-000047","ACH-000979","ACH-001024")]
#which(rownames(prism.cnv)=="ACH-001024")
#85, 268, 294,307
prism.cnv_corr_cleaned<- prism.cnv[-c(85,268,294,307),]

#identify missing columns that are present in cnv but not in exp
diff_cols= setdiff(colnames(prism.cnv), colnames(prism.exp))
diff_cols= unique(c(diff_cols, setdiff(colnames(prism.exp), colnames(prism.cnv))))
print(diff_cols)

diff_cols2= setdiff(colnames(prism.exp), colnames(prism.cnv))
diff_cols2<- unique(c(diff_cols, setdiff(colnames(prism.cnv), colnames(prism.exp))))
prism.cnv_corr_cleaned<-prism.cnv_corr_cleaned[-which(colnames(prism.cnv) %in% diff_cols)]
prism.exp_corr_cleaned<-prism.exp[-which(colnames(prism.exp) %in% diff_cols2)]

#reorder rows in an ascending way
#1.step:rownames(prism.cnv_corr_cleaned)
prism.cnv_corr_cleaned<- prism.cnv_corr_cleaned[order(rownames(prism.cnv_corr_cleaned)),]
prism.exp_corr_cleaned<- prism.exp_corr_cleaned[order(rownames(prism.exp_corr_cleaned)),]

#reorder columns by names
prism.cnv_corr_cleaned= prism.cnv_corr_cleaned[,colnames(prism.exp_corr_cleaned)]
```


```{r entferne korrelierende gene}

# Berechnung der Korrelationsmatrix
cor_matrix= cor(as.matrix(prism.exp_corr_cleaned))

# Erzeugung einer leeren Matrix für die Aufbewahrung der entfernten Gene
removed_genes= matrix(nrow = 0, ncol = 1)

# Schleife über die Korrelationsmatrix
for (i in 1:(ncol(cor_matrix) - 1)) {
  for (j in (i + 1):ncol(cor_matrix)) {
    # Prüfung auf hohe Korrelation
    if (!is.na(cor_matrix[i, j]) && abs(cor_matrix[i, j]) >= 0.8) {
      # Zufällige Auswahl eines Gens zum Entfernen
      remove_gene= sample(c(colnames(cor_matrix)[i], colnames(cor_matrix)[j]), 1)
      removed_genes= rbind(removed_genes, remove_gene)
    }
  }
}

# Ausgabe der entfernten Gen-Namen
removed_gene_names= as.vector(removed_genes)
length(removed_gene_names)

prism.exp_corr_cleaned_c= prism.exp_corr_cleaned[-which(colnames(prism.exp_corr_cleaned) %in% removed_gene_names)]
prism.cnv_corr_cleaned_c= prism.cnv_corr_cleaned[-which(colnames(prism.cnv_corr_cleaned) %in% removed_gene_names)]
```

```{r  NOT WORKING::Lineare Regression zur Vorhersage der Expressionsdaten aus den CNV-Daten}
library(dplyr)
library(tidyr)
library(stats)
library(caret)

# Aufteilen der Daten in Trainings- und Testdaten
set.seed(123)  # Für die Reproduzierbarkeit
train_indices= createDataPartition(y = 1:ncol(prism.cnv_corr_cleaned_c), p = 0.7, list = FALSE)
train.data.exp= as.data.frame(prism.exp_corr_cleaned_c[,train_indices ])
test.data.exp= as.data.frame(prism.exp_corr_cleaned_c[,-train_indices ])
train.data.cnv= prism.cnv_corr_cleaned_c[,train_indices ]
test.data.cnv= prism.cnv_corr_cleaned_c[,-train_indices ]



# Lineare Regression
model= lm(train.data.exp ~ train.data.cnv, 
          data = train.data.cnv, train.data.exp)

# Vorhersage der Genexpression basierend auf den CNV-Daten
predicted_expression= predict(model, newdata = new.test.data.exp)

# Ergebnis anzeigen
predicted_expression




```

```{r}
# Aufteilen der Daten in Trainings- und Testdaten
set.seed(123)
train_indice= createDataPartition(y = colnames(prism.cnv_corr_cleaned_c), p = 0.7, list = FALSE)
train.data.exp= prism.exp_corr_cleaned_c[, train_indices]
test.data.exp= prism.exp_corr_cleaned_c[, -train_indices]
train.data.cnv= prism.cnv_corr_cleaned_c[, train_indices]
test.data.cnv= prism.cnv_corr_cleaned_c[, -train_indices]

# Lineare Regression
formula= as.formula(paste(colnames(train.data.exp), "~", paste(colnames(train.data.cnv), collapse = "+")))
model= lm(formula, data = data.frame(train.data.exp, train.data.cnv))

# Vorhersage der Genexpression basierend auf den CNV-Daten
predicted_expression <- predict(model, newdata = data.frame(train.data.cnv))

# Ergebnis anzeigen
predicted_expression


```
